[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mrap"
authors = [
    {name = "Olga Lezhnina", email = "olga.lezhnina@tib.eu"},
    {name = "Manuel Prinz", email = "manuel.prinz@tib.eu"},
    {name = "Markus Stocker", email = "markus.stocker@tib.eu"},
]
maintainers = [
    {name = "Olga Lezhnina", email = "olga.lezhnina@tib.eu"}
]
description = "Machine-Radable Data Analysis Results with Function Wrappers"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["wrappers", "schema", "JSON-LD"]
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "dtreg",
    "pandas",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/OlgaLezhnina/mrap_py"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"dtreg.data" = ["*.json", "src/dtreg/data/*"]

[tool.setuptools_scm]